@HotelListing.Api_HostAddress = https://localhost:7275

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "id" : 1,
  "name": "Grand Plaza",
  "address": "123 Main St",
  "rating" : 4.5
}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels/2

###

@id=1
DELETE {{HotelListing.Api_HostAddress}}/api/hotels/1

###

PUT {{HotelListing.Api_HostAddress}}/api/hotels/1
Content-Type: application/json

{
  "id" : 1,
  "name": "Test Hotel Plaza",
  "address": "123 Main St",
  "rating" : 4.5
}